export enum SocketEvents {
  CONNECT = "CONNECT",
  DISCONNECT = "DISCONNECT",
  REGISTER_CHAT_ID = "REGISTER_CHAT_ID",
  SEARCH_GAME = "SEARCH_GAME",
  PLAYER_MOVE = "PLAYER_MOVE",
  GAME_OVER = "GAME_OVER",
  GAME_START = "GAME_START",
  ERROR = "ERROR",
  OPPONENT_MOVE = "OPPONENT_MOVE",
  ROUND_RESULT = "ROUND_RESULT",
  ROUND_START = "ROUND_START",
}

export enum UserMove {
  PAPER = "PAPER",
  SCISSOR = "SCISSOR",
  ROCK = "ROCK",
  RANDOM = "RANDOM",
}
export enum AlertEnum {
  SUCCESS = "success",
  ERROR = "error",
}
